### ISSUE TITLE
[phpcs-PSR-4-sniff] Conflict with slevomat/coding-standard 5

### ISSUE THREAD

**Issue by JanMikes** [suin/php#1]
Hello!

We are using https://packagist.org/packages/symplify/easy-coding-standard and it requires `slevomat/coding-standard` in version of 5.

Now i am playing around with the `SlevomatCodingStandard\Sniffs\Files\TypeNameMatchesFileNameSniff` but would love to try your sniff instead.

Why does this package conflict with version 5 of slevomat/coding-standard?

**Comment by suin** [comment]
@JanMikes When I released this package, [`easy-coding-standard` required `slevomat/coding-standard#^4.8`](https://packagist.org/packages/symplify/easy-coding-standard#v5.4.13). So this package was declared as a dependent on `slevomat/coding-standard` v4 following a way of the semantic versioning.

I'm wondering if there are actual compatibilities between this package and `slevomat/coding-standard` v5. If it is so, it would better to change the statement of the package dependency of this package.

**Comment by JanMikes** [comment]
Thank you for your answer!

Is it good enough if i upgrade composer version constraints, try running it and if tests passes it is okay? Anything else in your mind?
